package com.system.entity;
import javax.persistence.Id;
public class Training {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training.trainID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    @Id
    private Integer trainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training.trDescription
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    private String trdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training.courseID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training.teaID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    private Integer teaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training.trainID
     *
     * @return the value of training.trainID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public Integer getTrainid() {
        return trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training.trainID
     *
     * @param trainid the value for training.trainID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public void setTrainid(Integer trainid) {
        this.trainid = trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training.trDescription
     *
     * @return the value of training.trDescription
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public String getTrdescription() {
        return trdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training.trDescription
     *
     * @param trdescription the value for training.trDescription
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public void setTrdescription(String trdescription) {
        this.trdescription = trdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training.courseID
     *
     * @return the value of training.courseID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training.courseID
     *
     * @param courseid the value for training.courseID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training.teaID
     *
     * @return the value of training.teaID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training.teaID
     *
     * @param teaid the value for training.teaID
     *
     * @mbggenerated Wed Apr 08 12:13:51 CST 2020
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }
}